version: '3'
services:
    hasher_server:
      build:
        context: hasher_server
      environment:
        - HASH_SERVICE_PORT=${HASH_SERVICE_PORT}
      ports:
        - ${HASH_SERVICE_PORT}:${HASH_SERVICE_PORT}
    client:
      build:
        context: client
      environment:
        - CLIENT_PORT=${CLIENT_PORT}
        - HASH_SERVICE_PORT=${HASH_SERVICE_PORT}
        - HASH_SERVICE_HOST=${HASH_SERVICE_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - DB_TYPE=${DB_TYPE}
        - DB_HOST=${DB_HOST}
      ports:
        - ${CLIENT_PORT}:${CLIENT_PORT}
      depends_on:
        - database
    database:
      image: postgres:latest
      container_name: database
      environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=${DB_NAME}
      ports:
        - ${DB_PORT}:${DB_PORT}
      volumes:
        - pg-data:/var/lib/postgresql/data
volumes:
  pg-data:
    driver: local